project_name: zmk-viewer

builds:
  - skip: true
    goos:
      - "linux"
      - "windows"
      - "darwin"

release:
  github:
    owner: mrmarble
    name: zmk-viewer

archives:
  - format: tar.gz
    id: darwin-amd64
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-darwin-amd64'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-darwin-amd64'
  - format: tar.gz
    id: darwin-arm64
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-darwin-arm64'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-darwin-arm64'
  - format: tar.gz
    id: linux-386
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-linux-386'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-linux-386'
  - format: tar.gz
    id: linux-amd64
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-linux-amd64'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-linux-amd64'
  - format: tar.gz
    id: linux-arm64
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-linux-arm64'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-linux-arm64'
  - format: zip
    id: windows-386
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-windows-386'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-windows-386.exe'
  - format: zip
    id: windows-amd64
    meta: true
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-windows-amd64'
    files:
      - LICENSE
      - README.md
      - '{{ .ProjectName }}-v{{ .Version }}-windows-amd64.exe'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
